title: Peyman Jabbarzade
position: Ph.D. Student
affiliation: University of Maryland
email: peymanj (at) umd.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=waMTjQcAAAAJ
github_link: https://github.com/pjabbarzade
linkedin: https://www.linkedin.com/in/peyman-j-1566a991/
university_webpage: https://www.cs.umd.edu/people/peymanj
cv_link: ./assets/files/CV.pdf
avatar: ./assets/img/avatar.jpeg
google_analytics: 
favicon: ./assets/img/pj-light.jpeg
favicon_dark: ./assets/img/pj-dark.jpeg
description: The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
