title: Peyman Jabbarzade
position: Ph.D. Student
affiliation: University of Maryland
email: peymanj (at) umd.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=waMTjQcAAAAJ
github_link: https://github.com/pjabbarzade
linkedin: https://www.linkedin.com/in/peyman-j-1566a991/
cv_link: ./assets/files/CV.pdf
avatar: ./assets/img/avatar.jpeg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
